title: Yuta Takimoto
description: Portfolio
url: "https://takimoto-pf.github.io"
theme: null          # 既定テーマを外す＝独自テンプレ前提
plugins: []          # Pages標準のまま
sass:
  sass_dir: _sass        # ← これがポイント
  style: compressed
collections:
  hyougen:
    output: true
    permalink: /hyougen/:name/